/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * RatingCurvesResponse PI_JSON
 */
export interface RatingCurvesResponse {
  /**
   * the timezone
   */
  timeZone?: string;
  ratingCurves: RatingCurve[];
}
export interface RatingCurve {
  header: RatingCurveHeader;
  table?: RatingCurveTable;
  equations?: RatingCurveEquation[];
}
export interface RatingCurveHeader {
  /**
   * Location Id
   */
  locationId: string;
  qualifierIds?: string[];
  startDate: RatingCurveDate;
  endDate?: RatingCurveDate;
  /**
   * Long Name
   */
  longName?: string;
  /**
   * Station Name
   */
  stationName?: string;
  /**
   * Stage Unit
   */
  stageUnit: string;
  /**
   * Discharge Unit
   */
  dischargeUnit: string;
  /**
   * Source Organization
   */
  sourceOrganisation?: string;
  /**
   * Source System
   */
  sourceSystem?: string;
  /**
   * File Descriptor
   */
  fileDescription?: string;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Creation Date
   */
  creationDate?: string;
  /**
   * Creation Time
   */
  creationTime?: string;
  /**
   * Region
   */
  region?: string;
}
/**
 * Date
 */
export interface RatingCurveDate {
  /**
   * Date
   */
  date: string;
  /**
   * Time
   */
  time: string;
}
export interface RatingCurveTable {
  /**
   * Interpolation method. For example: linear
   */
  interpolationMethod: string;
  /**
   * Minimum stage value. -INF for negative infinity and INF for positive infinity
   */
  minStage: string;
  /**
   * Maximum stage value. -INF for negative infinity and INF for positive infinity
   */
  maxStage: string;
  /**
   * RatingCurveRow
   */
  rows: RatingCurveRow[];
}
export interface RatingCurveRow {
  /**
   * Stage value. -INF for negative infinity and INF for positive infinity
   */
  stage: string;
  /**
   * Discharge value. -INF for negative infinity and INF for positive infinity
   */
  discharge: string;
  /**
   * Log Scale Offset. -INF for negative infinity and INF for positive infinity
   */
  logScaleStageOffset?: string;
  /**
   * Flag
   */
  flag?: string;
}
export interface RatingCurveEquation {
  /**
   * Equation type. Currently only powerEquation is supported.
   */
  type: "powerEquation";
  /**
   * Minimum stage value. -INF for negative infinity and INF for positive infinity
   */
  minStage: string;
  /**
   * Maximum stage value. -INF for negative infinity and INF for positive infinity
   */
  maxStage: string;
  /**
   * Flag
   */
  flag: string;
  /**
   * Alpha
   */
  alpha: string;
  /**
   * Cr
   */
  cr: string;
  /**
   * Beta
   */
  beta: string;
}
