/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ArchiveExternalNetCDFStorageForecastsResponse PI_JSON
 */
export interface ArchiveExternalNetCDFStorageForecasts {
  /**
   * External NetCD FStorage Forecasts
   */
  externalNetCDFStorageForecasts: ExternalNetCDFStorageForecast[];
}
export interface ExternalNetCDFStorageForecast {
  forecastTime: string;
  forecastAvailableTime: string;
  /**
   * External NetCD FStorage Forecasts Attributes
   */
  attributes?: ExternalNetCDFStorageForecastAttribute[];
}
export interface ExternalNetCDFStorageForecastAttribute {
  name: string;
  value: string;
}
