/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ArchiveAttributesResponse PI_JSON
 */
export interface ArchiveAttributes {
  /**
   * ArchiveAttributes
   */
  archiveAttributes: ArchiveAttribute[];
}
export interface ArchiveAttribute {
  name: string;
  value: string;
}
