/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * LocationsResponse GEO_JSON
 */
export interface LocationsResponseGeoJson {
  /**
   * Type
   */
  type: "FeatureCollection";
  crs: LocationGeoJsonCrs;
  /**
   * LocationGeoJsonFeatures
   */
  features: LocationGeoJsonFeature[];
}
/**
 * The geo datum
 */
export interface LocationGeoJsonCrs {
  /**
   * the id of the location
   */
  type: string;
  properties: LocationGeoJsonCrsProperty;
}
export interface LocationGeoJsonCrsProperty {
  /**
   * the EPSG code
   */
  code: number;
}
export interface LocationGeoJsonFeature {
  /**
   * the id of the location
   */
  type: string;
  geometry: LocationGeoJsonGeometry;
  properties: LocationGeoJsonFeatureProperties;
}
/**
 * GeoJSon geometry
 */
export interface LocationGeoJsonGeometry {
  /**
   * the geometry type
   */
  type: "Point";
  [k: string]: unknown;
}
export interface LocationGeoJsonFeatureProperties {
  /**
   * the id of the location
   */
  locationId: string;
  /**
   * The location name
   */
  locationName?: string;
  /**
   * The description of the locations
   */
  description?: string;
  /**
   * The Short name of the location
   */
  shortName?: string;
  /**
   * Start date time in case a time dependent relation is use
   */
  startDateTime?: string;
  /**
   * End date time in case a time dependent relation is use
   */
  endDateTime?: string;
  /**
   * Latitude
   */
  lat?: string;
  /**
   * Longitude
   */
  lon?: string;
  /**
   * X
   */
  x?: string;
  /**
   * Y
   */
  y?: string;
  /**
   * Z
   */
  z?: string;
  /**
   * Location Attributes
   */
  attributes?: LocationGeoJsonAttributes[];
  /**
   * Related Locations
   */
  relations?: LocationGeoJsonRelation[];
  /**
   * Id of the parent location
   */
  parentLocationId?: string;
}
export interface LocationGeoJsonAttributes {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Type
   */
  type?: "text" | "boolean" | "number" | "dateTime";
  /**
   * Id
   */
  id?: string;
  /**
   * Start date time
   */
  startDateTime?: string;
  /**
   * End date time
   */
  endDateTime?: string;
  /**
   * Value
   */
  value?: string;
}
export interface LocationGeoJsonRelation {
  /**
   * Id
   */
  id?: string;
  /**
   * Related Location Id
   */
  relatedLocationId: string;
  /**
   * Start date time
   */
  startDateTime?: string;
  /**
   * End date time
   */
  endDateTime?: string;
}
