/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * WarmStateTimesResponse PI_JSON
 */
export interface WarmStateTimesResponse {
  warmStateTimes?: WarmStateTime[];
  [k: string]: unknown;
}
export interface WarmStateTime {
  /**
   * the module instance id for which the warm state times should be retrieved
   */
  moduleInstanceId: string;
  /**
   * warm state times
   */
  times: string[];
}
