/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * TimeSeriesFlagSources PI_JSON
 */
export interface TimeSeriesFlagSourcesResponse {
  flagSources?: TimeSeriesFlagSource[];
}
export interface TimeSeriesFlagSource {
  /**
   * the id of the flag
   */
  id: string | null;
  /**
   * Name of the flag
   */
  name: string;
}
