/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * TimeSeriesFlags PI_JSON
 */
export interface TimeSeriesFlagsResponse {
  flags?: TimeSeriesFlag[];
}
export interface TimeSeriesFlag {
  /**
   * the name of the flag
   */
  flag: number;
  /**
   * Name of the flag
   */
  name: string;
  source: "ORIGINAL" | "CORRECTED" | "COMPLETED" | null;
  quality: "RELIABLE" | "DOUBTFUL" | "UNRELIABLE" | null;
}
