/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ImportStatusResponse PI_JSON
 */
export interface ImportStatusResponse {
  importStatus: ImportStatus[];
  [k: string]: unknown;
}
export interface ImportStatus {
  mcId: string;
  dataFeed: string;
  lastImportTime: string;
  lastFileImported: string;
  fileRead: number;
  fileFailed: number;
  lastImportTimeBackgroundColor: string;
}
