/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ArchiveProductsMetadataResponse PI_JSON
 */
export interface ArchiveProductsMetadata {
  /**
   * Archive Products Metadata
   */
  productsMetadata: ArchiveProductsMetadataEntry[];
}
export interface ArchiveProductsMetadataEntry {
  version?: string;
  areaId: string;
  sourceId: string;
  relativePathMetaDataFile: string;
  /**
   * Relative Path Products
   */
  relativePathProducts: string[];
  dataSetCreationTime?: string;
  timeZero?: string;
  /**
   * Archive Products Metadata Attributes
   */
  attributes: ArchiveProductsMetadataAttribute[];
}
export interface ArchiveProductsMetadataAttribute {
  key: string;
  value: string;
}
