/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ActionsResponse PI_JSON
 */
export interface ActionsResponse {
  resultsNotAvailableForRequest?: boolean;
  /**
   * ActionsResults
   */
  results: Action[];
}
export interface Action {
  type: "PI";
  /**
   * ActionRequests
   */
  requests: ActionRequest[];
  config?: ActionRequestConfig;
}
export interface ActionRequest {
  key: string;
  request: string;
}
export interface ActionRequestConfig {
  timeSeriesDisplay: TimeSeriesDisplayConfig;
}
export interface TimeSeriesDisplayConfig {
  title: string;
  subplots: TimeSeriesDisplaySubplot[];
}
export interface TimeSeriesDisplaySubplot {
  items: TimeSeriesDisplaySubplotItem[];
}
export interface TimeSeriesDisplaySubplotItem {
  type: string;
  legend?: string;
  color?: string;
  lineStyle?: string;
  lineWidth?: number;
  locationId?: string;
  yAxis?: TimeSeriesDisplaySubplotAxis;
  /**
   * Key of the request
   */
  request: string;
}
export interface TimeSeriesDisplaySubplotAxis {
  axisPosition: string;
  axisLabel: string;
}
