/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ArchiveLocationsResponse PI_JSON
 */
export interface ArchiveLocations {
  /**
   * ArchiveLocation
   */
  locations: ArchiveLocation[];
}
export interface ArchiveLocation {
  locationId: string;
  shortName?: string;
  lat: string;
  lon: string;
}
