/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ArchiveSourcesResponse PI_JSON
 */
export interface ArchiveSources {
  /**
   * ArchiveSource
   */
  sources: ArchiveSource[];
}
export interface ArchiveSource {
  id: string;
  name: string;
}
