/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Time step
 */
export type TimeStep =
  | {
      /**
       * Unit
       */
      unit: string;
      /**
       * Multiplier
       */
      multiplier?: string;
    }
  | {
      /**
       * Times
       */
      times: string;
    }
  | {
      /**
       * Minutes
       */
      minutes: string;
    };
export type OriginalReliable = "0";
export type CorrectedReliable = "1";
export type CompletedReliable = "2";
export type OriginalDoubtful = "3";
export type CorrectedDoubtful = "4";
export type CompletedDoubtful = "5";
export type OriginalUnreliable = "6";
export type CorrectedUnreliable = "7";
export type CompletedUnreliable = "8";
export type OriginalMissing = "9";
export type Deleted = "10";
export type SetOriginalReliable = "11";
export type SetOriginalUnreliable = "12";
export type ArchiveMissing = "13";
export type MANUAL = "MAN";
export type IMPORTED = "IMP";
export type MODIFIER = "MOD";
export type SOFT_MIN = "SN";
export type HARD_MIN = "HN";
export type SOFT_MAX = "SX";
export type HARD_MAX = "HX";
export type RATE_OF_RISE = "ROR";
export type RATE_OF_FALL = "ROF";
export type SAME_READING = "SR";
export type TEMPORARY_SHIFT = "TS";
export type SERIES_COMPARISON = "SC";
export type FLAGS_COMPARISON = "FC";
export type SPATIAL_HOMOGENEITY = "SH";
export type MANN_KENDALL = "MK";
export type START_FLAG_PERSISTENCY = "SFP";
export type SECONDARY_VALIDATION_FLAG_PERSISTENCY = "SVP";
export type CONDITIONAL_AGGREGATION = "CA";
export type OSCILLATION = "OSC";
export type NONE = null;
/**
 * array of strings
 */
export type DomainAxisValueStringArray = string[];
/**
 * Domain Axis Value Array
 */
export type DomainAxisValueArray = DomainAxisValueStringArray[];
/**
 * array of strings
 */
export type DomainAxisEventValuesStringArray = string[];
/**
 * array of arrays
 */
export type DomainAxisEventValuesArray = DomainAxisEventValuesStringArray[];

/**
 * TimeSeries PI_JSON
 */
export interface TimeSeriesResponse {
  /**
   * PI Version
   */
  version: string;
  /**
   * Time Zone of the timeSeries times
   */
  timeZone?: string;
  /**
   * Time series data represent data collected over a given period of time at a specific location
   */
  timeSeries?: TimeSeriesResult[];
}
export interface TimeSeriesResult {
  header?: Header;
  properties?: TimeSeriesProperty[];
  /**
   * Events
   */
  events?: TimeSeriesEvent[];
  /**
   * Domains
   */
  domains?: Domains[];
}
/**
 * The header
 */
export interface Header {
  /**
   * TimeSeries type
   */
  type: string;
  /**
   * Module Instance Id
   */
  moduleInstanceId?: string;
  /**
   * Location id
   */
  locationId: string;
  /**
   * Parameter id
   */
  parameterId: string;
  /**
   * Qualifier Id
   */
  qualifierId?: string[];
  /**
   * Ensemble Id. Can be followed by either a ensembleMemberIndex or ensembleMemberId
   */
  ensembleId?: string;
  /**
   * Ensemble Member Index
   */
  ensembleMemberIndex?: string;
  /**
   * Ensemble Member Id
   */
  ensembleMemberId?: string;
  timeStep?: TimeStep;
  startDate: FewsDate;
  endDate: FewsDate;
  forecastDate?: FewsDate;
  /**
   * Missing value
   */
  missVal: string;
  /**
   * Long name
   */
  longName?: string;
  /**
   * Station name
   */
  stationName?: string;
  /**
   * Latitude
   */
  lat?: string;
  /**
   * Longitude
   */
  lon?: string;
  /**
   * X
   */
  x?: string;
  /**
   * Y
   */
  y?: string;
  /**
   * Z
   */
  z?: string;
  /**
   * Units
   */
  units?: string;
  /**
   * Domain Axis
   */
  domainAxis?: DomainAxis[];
  /**
   * Source Organisation
   */
  sourceOrganisation?: string;
  /**
   * Source System
   */
  sourceSystem?: string;
  /**
   * File Descriptor
   */
  fileDescription?: string;
  /**
   * Creation date
   */
  creationDate?: string;
  /**
   * Creation time
   */
  creationTime?: string;
  approvedDate?: FewsDate;
  /**
   * Region
   */
  region?: string;
  /**
   * Thresholds
   */
  thresholds?: TimeSeriesThreshold[];
  firstValueTime?: FewsDate;
  lastValueTime?: FewsDate;
  /**
   * Max value
   */
  maxValue?: string;
  /**
   * Min value
   */
  minValue?: string;
  /**
   * Value count
   */
  valueCount?: string;
  /**
   * Max Warning Level Name
   */
  maxWarningLevelName?: string;
  product?: Product;
}
/**
 * Date
 */
export interface FewsDate {
  /**
   * Date
   */
  date: string;
  /**
   * Time
   */
  time: string;
}
export interface DomainAxis {
  /**
   * Parameter Id
   */
  parameterId: string;
  /**
   * Units
   */
  units?: string;
}
/**
 * Threshold
 */
export interface TimeSeriesThreshold {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name?: string;
  /**
   * Label
   */
  label?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Value
   */
  value?: string;
  /**
   * Type
   */
  type?: string;
  /**
   * Group Id
   */
  groupId?: string;
  /**
   * Group Name
   */
  groupName?: string;
}
/**
 * Date
 */
export interface Product {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Product Date
   */
  productDate: string;
  /**
   * Product Time
   */
  productTime: string;
  /**
   * Category
   */
  category: {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
  };
  /**
   * Product Info
   */
  productInfo?: {
    /**
     * User
     */
    user: string;
    /**
     * Confidence
     */
    confidence: string;
    /**
     * Classification
     */
    classification: string;
    /**
     * Comment
     */
    comment: string;
  }[];
}
/**
 * Property
 */
export interface TimeSeriesProperty {
  [k: string]: unknown;
}
/**
 * Timeseries event
 */
export interface TimeSeriesEvent {
  /**
   * Date
   */
  date: string;
  /**
   * Time
   */
  time: string;
  /**
   * Start Date
   */
  startDate?: string;
  /**
   * Start Time
   */
  startTime?: string;
  /**
   * End Date
   */
  endDate?: string;
  /**
   * End Time
   */
  endTime?: string;
  /**
   * Value
   */
  value: string;
  /**
   * Minimum Value
   */
  minValue?: string;
  /**
   * Maximum Value
   */
  maxValue?: string;
  /**
   * Detection Symbol
   */
  detection?: string;
  /**
   * Flag
   */
  flag:
    | OriginalReliable
    | CorrectedReliable
    | CompletedReliable
    | OriginalDoubtful
    | CorrectedDoubtful
    | CompletedDoubtful
    | OriginalUnreliable
    | CorrectedUnreliable
    | CompletedUnreliable
    | OriginalMissing
    | Deleted
    | SetOriginalReliable
    | SetOriginalUnreliable
    | ArchiveMissing;
  /**
   * Flag Source
   */
  flagSource?:
    | MANUAL
    | IMPORTED
    | MODIFIER
    | SOFT_MIN
    | HARD_MIN
    | SOFT_MAX
    | HARD_MAX
    | RATE_OF_RISE
    | RATE_OF_FALL
    | SAME_READING
    | TEMPORARY_SHIFT
    | SERIES_COMPARISON
    | FLAGS_COMPARISON
    | SPATIAL_HOMOGENEITY
    | MANN_KENDALL
    | START_FLAG_PERSISTENCY
    | SECONDARY_VALIDATION_FLAG_PERSISTENCY
    | CONDITIONAL_AGGREGATION
    | OSCILLATION
    | NONE;
  /**
   * Flag Source Column
   */
  flagSourceColumn?: {
    [k: string]: unknown;
  };
  /**
   * Comment
   */
  comment?: string;
  /**
   * User
   */
  user?: string;
}
/**
 * Domains
 */
export interface Domains {
  /**
   * Domain Axis Values
   */
  domainAxisValues?: DomainAxisValue[];
  /**
   * Domain Axis Events
   */
  events?: DomainAxisEvent[];
}
/**
 * Domain Axis Value
 */
export interface DomainAxisValue {
  /**
   * Parameter Id
   */
  parameterId?: string;
  values?: DomainAxisValueArray;
}
/**
 * Domain Axis Event Array
 */
export interface DomainAxisEvent {
  /**
   * Date
   */
  date?: string;
  /**
   * Time
   */
  time?: string;
  /**
   * Flag
   */
  flag?: string;
  values?: DomainAxisEventValuesArray;
}
