/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Time step
 */
export type TimeStep =
  | {
      /**
       * Unit
       */
      unit: string;
      /**
       * Multiplier
       */
      multiplier?: string;
    }
  | {
      /**
       * Times
       */
      times: string;
    }
  | {
      /**
       * Minutes
       */
      minutes: string;
    };
/**
 * array of strings
 */
export type DomainAxisValueStringArray = string[];
/**
 * Domain Axis Value Array
 */
export type DomainAxisValueArray = DomainAxisValueStringArray[];
/**
 * array of strings
 */
export type DomainAxisEventValuesStringArray = string[];
/**
 * array of arrays
 */
export type DomainAxisEventValuesArray = DomainAxisEventValuesStringArray[];

/**
 * TimeSeries PI_JSON
 */
export interface TimeSeriesResponse {
  /**
   * PI Version
   */
  version: string;
  /**
   * Time Zone of the timeSeries times
   */
  timeZone?: string;
  /**
   * Time series data represent data collected over a given period of time at a specific location
   */
  timeSeries?: TimeSeriesResult[];
}
export interface TimeSeriesResult {
  header?: Header;
  properties?: Property[];
  /**
   * Events
   */
  events?: Event[];
  /**
   * Domains
   */
  domains?: Domains[];
}
/**
 * The header
 */
export interface Header {
  /**
   * TimeSeries type
   */
  type: string;
  /**
   * Module Instance Id
   */
  moduleInstanceId?: string;
  /**
   * Location id
   */
  locationId: string;
  /**
   * Parameter id
   */
  parameterId: string;
  /**
   * Qualifier Id
   */
  qualifierId?: string[];
  /**
   * Ensemble Id. Can be followed by either a ensembleMemberIndex or ensembleMemberId
   */
  ensembleId?: string;
  /**
   * Ensemble Member Index
   */
  ensembleMemberIndex?: string;
  /**
   * Ensemble Member Id
   */
  ensembleMemberId?: string;
  timeStep?: TimeStep;
  startDate: FewsDate;
  endDate: FewsDate;
  forecastDate?: FewsDate;
  /**
   * Missing value
   */
  missVal: string;
  /**
   * Long name
   */
  longName?: string;
  /**
   * Station name
   */
  stationName?: string;
  /**
   * Latitude
   */
  lat?: string;
  /**
   * Longitude
   */
  lon?: string;
  /**
   * X
   */
  x?: string;
  /**
   * Y
   */
  y?: string;
  /**
   * Z
   */
  z?: string;
  /**
   * Units
   */
  units?: string;
  /**
   * Domain Axis
   */
  domainAxis?: DomainAxis[];
  /**
   * Source Organisation
   */
  sourceOrganisation?: string;
  /**
   * Source System
   */
  sourceSystem?: string;
  /**
   * File Descriptor
   */
  fileDescription?: string;
  /**
   * Creation date
   */
  creationDate?: string;
  /**
   * Creation time
   */
  creationTime?: string;
  approvedDate?: FewsDate;
  /**
   * Region
   */
  region?: string;
  /**
   * Thresholds
   */
  thresholds?: TimeSeriesThreshold[];
  firstValueTime?: FewsDate;
  lastValueTime?: FewsDate;
  /**
   * Max value
   */
  maxValue?: string;
  /**
   * Min value
   */
  minValue?: string;
  /**
   * Value count
   */
  valueCount?: string;
  /**
   * Max Warning Level Name
   */
  maxWarningLevelName?: string;
  product?: Product;
}
/**
 * Date
 */
export interface FewsDate {
  /**
   * Date
   */
  date: string;
  /**
   * Time
   */
  time: string;
}
export interface DomainAxis {
  /**
   * Parameter Id
   */
  parameterId: string;
  /**
   * Units
   */
  units?: string;
}
/**
 * Threshold
 */
export interface TimeSeriesThreshold {
  /**
   * Id
   */
  id?: string;
  /**
   * Name
   */
  name?: string;
  /**
   * Label
   */
  label?: string;
  /**
   * Description
   */
  description?: string;
  /**
   * Comment
   */
  comment?: string;
  /**
   * Value
   */
  value?: string;
  /**
   * Type
   */
  type?: string;
  /**
   * Group Id
   */
  groupId?: string;
  /**
   * Group Name
   */
  groupName?: string;
}
/**
 * Date
 */
export interface Product {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Product Date
   */
  productDate: string;
  /**
   * Product Time
   */
  productTime: string;
  /**
   * Category
   */
  category: {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
  };
  /**
   * Product Info
   */
  productInfo?: {
    /**
     * User
     */
    user: string;
    /**
     * Confidence
     */
    confidence: string;
    /**
     * Classification
     */
    classification: string;
    /**
     * Comment
     */
    comment: string;
  }[];
}
/**
 * Property
 */
export interface Property {
  [k: string]: unknown;
}
/**
 * Timeseries event
 */
export interface Event {
  /**
   * Date
   */
  date: string;
  /**
   * Time
   */
  time: string;
  /**
   * Start Date
   */
  startDate?: string;
  /**
   * Start Time
   */
  startTime?: string;
  /**
   * End Date
   */
  endDate?: string;
  /**
   * End Time
   */
  endTime?: string;
  /**
   * Value
   */
  value: string;
  /**
   * Minimum Value
   */
  minValue?: string;
  /**
   * Maximum Value
   */
  maxValue?: string;
  /**
   * Detection Symbol
   */
  detection?: string;
  /**
   * Flag
   */
  flag: string;
  /**
   * Flag
   */
  flagSource?: string;
  /**
   * Flag Source Column
   */
  flagSourceColumn?: {
    [k: string]: unknown;
  };
  /**
   * Comment
   */
  comment?: string;
  /**
   * User
   */
  user?: string;
}
/**
 * Domains
 */
export interface Domains {
  /**
   * Domain Axis Values
   */
  domainAxisValues?: DomainAxisValue[];
  /**
   * Domain Axis Events
   */
  events?: DomainAxisEvent[];
}
/**
 * Domain Axis Value
 */
export interface DomainAxisValue {
  /**
   * Parameter Id
   */
  parameterId?: string;
  values?: DomainAxisValueArray;
}
/**
 * Domain Axis Event Array
 */
export interface DomainAxisEvent {
  /**
   * Date
   */
  date?: string;
  /**
   * Time
   */
  time?: string;
  /**
   * Flag
   */
  flag?: string;
  values?: DomainAxisEventValuesArray;
}
