export enum TimeSeriesType {
    EXTERNAL_HISTORICAL = 'EXTERNAL_HISTORICAL',
    EXTERNAL_FORECASTING = 'EXTERNAL_FORECASTING',
    SIMULATED_HISTORICAL = 'SIMULATED_HISTORICAL',
    SIMULATED_FORECASTING = 'SIMULATED_FORECASTING',
}
